### ISSUE TITLE
Custom multiedit cursors

### ISSUE THREAD

**Issue by kozikow** [hlissner/evil-multiedit#11]
Is there a way of starting evil-multiedit on custom cursors?
Sometimes I want to start multiedit at the end of the begging of the line, rather than just on the "match" of some keyword.

evil-mc for example have evil-mc-make-cursor-here, but I prefer evil-multiedit for other reasons.

**Comment by hlissner** [comment]
I had planned to add that feature, but haven't studied iedit enough. I'll look into it this or next weekend.

**Comment by hlissner** [comment]
This feature has been in evil-multiedit for a while, albeit rudimentary. Arbitrary iedit regions can be placed with `evil-multiedit-toggle-marker-here`. For that reason, I'm going to close this issue. 

That said, with the exception of bug fixes, I'm unsure of where to go with this feature. I've grown accustomed to using `evil-mc`, and I feel it and my plugin complement each other nicely. I'm also not too keen on reinventing the wheel. I may revisit it in the future, but for the time I'll consider this put on the backburner.
