### ISSUE TITLE
nil evil-multiedit-store-in-search-history ineffectual

### ISSUE THREAD

**Issue by braham-snyder** [hlissner/evil-multiedit#12]
I think I might stick with this behavior after all, but: despite setting `evil-multiedit-store-in-search-history` to `nil`, multiedit-matched text is saved to my search history (searching with <kbd>/</kbd>, matching different text with <kbd>M-d</kbd>, then pressing <kbd>n</kbd> takes me to the text I matched with <kbd>M-d</kbd>, not the text I searched using <kbd>/</kbd>)

thanks for the package!

**Comment by hlissner** [comment]
Sorry for taking so long, but this should be fixed now. Feel free to reopen if it isn't.
