### ISSUE TITLE
Symbol's value as variable is void: evil-multiedit-state-map

### ISSUE THREAD

**Issue by babygau** [hlissner/evil-multiedit#13]
hi,

i'm using `spacemacs` and got this error pop up in *message* buffer everytime i start the editor

`Symbol’s value as variable is void: evil-multiedit-state-map`

have you got any idea how to fix it?

**Comment by hlissner** [comment]
Ah, yes. Looks like there were changes upstream.

For now, you can fix this by adding the following anywhere before the `(require 'evil-multiedit)`:

```elisp
(defvar evil-multiedit-state-map (make-sparse-keymap))
;; preemptively fix a possible second issue
(defvar evil-multiedit-insert-state-map (make-sparse-keymap))
```

I'll let you know once I fix this in the package.

**Comment by babygau** [comment]
many thanks @hlissner 👍

**Comment by hlissner** [comment]
Looking over this now, and I can't seem to reproduce it. The fix above should still work though. Do you still have this problem without it?
