### ISSUE TITLE
The cursor behavior is different than normal when exist evil-multiedit-insert mode

### ISSUE THREAD

**Issue by dsdshcym** [hlissner/evil-multiedit#15]
Similar issue to https://github.com/syl20bnr/evil-iedit-state/issues/5

My guess is:
- evil-multiedit is calling evil-multiedit-state directly to go back to evil-multiedit "normal" mode
- which will not move back the cursor
- same things goes with evil-iedit-state-mode
- and evil-normal-state will call `evil-adjust-cursor` as a post-command and does something else to adjust the cursor position

My temporary solution for this is:
```elisp
  (general-define-key
   :keymaps 'evil-multiedit-insert-state-map
   "<escape>" (lambda () (interactive) (evil-multiedit-state) (evil-move-cursor-back)))
```

**Comment by hlissner** [comment]
Sorry for taking so long to notice this issue! I've incorporated your solution into evil-multiedit proper. I'll consider this issue resolved, but feel free to reopen it if you encounter any problems with it!

**Comment by dsdshcym** [comment]
Thanks a lot for the fix!

This solution has been working pretty well. (And I've already forgot I opened this issue)
