### ISSUE TITLE
Customize evil-multiedit-match-all to use text object

### ISSUE THREAD

**Issue by amosbird** [hlissner/evil-multiedit#16]
Hi, can I use evil-multiedit-match-all as an command that accepts a text object?

**Comment by hlissner** [comment]
I've added `evil-multiedit-operator`, which lets you select the target via text objects, however it wasn't given a default keybinding. I couldn't think of a good one, so I leave it up to the user. Something like:

```emacs-lisp
(define-key evil-normal-state-map (kbd "C-'") #'evil-multiedit-operator)
```

I'll consider this resolved. Feel free to reopen if the command doesn't work as expected.
