### ISSUE TITLE
Is it possible to convert evil-anzu selection to evil-multiedit?

### ISSUE THREAD

**Issue by amosbird** [hlissner/evil-multiedit#17]

**Comment by hlissner** [comment]
Sorry for the delayed reply. This _should_ be possible; I will look into it. For the time being, evil-multiedit has an ex command interface, `evil-multiedit-ex-match`. If you are using evil-multiedit's default keybindings, this should be bound to `:ie[dit]`, and accepts a regexp. e.g.

`:iedit a[bc]`

**Comment by amosbird** [comment]
This works in doom :)
```
(defun anzu-to-multiedit ()
  (interactive)
  (+evil|disable-highlights)
  (evil-multiedit-ex-match (point-min) (point-max) nil (car evil-ex-search-pattern)))
```
