### ISSUE TITLE
Customize the color

### ISSUE THREAD

**Issue by ema2159** [hlissner/evil-multiedit#27]
How can I customize the color of the selected areas? I couldn't find any documentation about

**Comment by hlissner** [comment]
evil-multiedit regions are iedit regions, and the iedit package uses the `iedit-occurrence` face to color iedit regions. This face is defined in iedit-lib.el as such:

```elisp
(defface iedit-occurrence
  '((t :inherit highlight))
  "*Face used for the occurrences' default values."
  :group 'iedit)
```

So you'll need to modify this face to modify the color of multiedit regions. e.g.

```elisp
(set-face-background 'iedit-occurrence "#FF0000")
```

Hope that helps!

**Comment by ema2159** [comment]
Sorry for not answering, I've been a little busy. That's indeed the solution, and even the foreground can be set using `(set-face-foreground 'iedit-occurrence "#000000")`. However it has to be after loading the theme! 
Thanks! You're pretty awesome. Thanks for taking the time to make Emacs even greater.
