### ISSUE TITLE
Typo in README? evil-visual-state-map binding

### ISSUE THREAD

**Issue by nfedyashev** [hlissner/evil-multiedit#32]
Usage binding from README doesn't seem to be working on my machine

>(define-key evil-visual-state-map (kbd "M-d") 'evil-multiedit-and-next)

but if I change it to

>(define-key evil-visual-state-map (kbd "M-d") 'evil-multiedit-match-and-next)

then it works great.

*Steps to reproduce:*

visually select some word(v), press meta-d

*Actual result:*
>Wrong type argument: commandp, evil-multiedit-and-next

Please let me know if you need some more context info.

**Comment by hlissner** [comment]
Good catch. It's meant to be `evil-multiedit-match-and-next` for both keys. I've corrected it in 88fa6b0. Thanks for bringing it to my attention!
