### ISSUE TITLE
Input method: Cannot type input method

### ISSUE THREAD

**Issue by triplc** [hlissner/evil-multiedit#35]
In normal insert mode, `C-\` works. But it does not seem to work in multiedit.

**Comment by hlissner** [comment]
`C-\` invokes `toggle-input-method` correctly for me in normal mode, multiedit mode and multiedit insert mode. I've tested this in vanilla Emacs with:

```elisp
(require 'evil)
(evil-mode)
(require 'evil-multiedit)
(evil-multiedit-default-keybinds)
```

The issue likely lies in your private config.
