### ISSUE TITLE
`evil-digit-bound-motions` was deleted

### ISSUE THREAD

**Issue by vmfhrmfoaj** [hlissner/evil-multiedit#45]
### What did you expect to happen?

No error when starting Emacs.

### What actually happened?

When starting Emacs, complain `evil-digit-bound-motions` is not declared.
It was deleted: https://github.com/emacs-evil/evil/commit/040210af0b3c9000ff9e552855322a1d35cebcf3

### Describe your attempts to resolve the issue

I think below line is no more needed.
```emacs-lisp
(add-to-list 'evil-digit-bound-motions 'evil-multiedit-beginning-of-line) ; line 479
```

workaround:
```emacs-lisp
(defvar evil-digit-bound-motions nil
  "`evil-digit-bound-motions' was deleted.
See, https://github.com/emacs-evil/evil/commit/040210af0b3c9000ff9e552855322a1d35cebcf3")
```

### Steps to reproduce

1. Update `evil` pacakge
2. Exit emacs
3. Start emacs

### Package commit

master

### System Information

I use Fedora Linux 35 (Workstation Edition) x86_64

**Comment by hlissner** [comment]
This issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
