### ISSUE TITLE
Multiple-cursors M-S-d is using iedit-delete-occurrences instead evil-multiedit-match-symbol-and-prev

### ISSUE THREAD

**Issue by otavioschwanck** [hlissner/evil-multiedit#46]
### What did you expect to happen?

Select a equal text before the cursor

### What actually happened?

Deleted the selected word

### Steps to reproduce

Create a text with:

1. doom_emacs_rulez
2. doom_emacs_rulez

Press M-d on the 2. doom_emacs_rulez
Press M-S-d

### System Information

https://pastebin.com/du740zYD

**Comment by hlissner** [comment]
Between 7400b67 and hlissner/doom-emacs@5241555, this issue should now be resolved. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!
