### ISSUE TITLE
Question: Why this line

### ISSUE THREAD

**Issue by justbur** [hlissner/evil-multiedit#6]
https://github.com/hlissner/evil-multiedit/blob/master/evil-multiedit.el#L281-L282

I don't understand the purpose of this. I have `evil-multiedit-thing-at-point-fn` to always grab symbols, but with this line if I try to use the match all function on the `-` of an elisp function, I only match all hyphens in the file, which is definitely not what I want ever. What is the purpose of this check in `evil-multiedit--match-bounds`?

**Comment by hlissner** [comment]
This was to allow people to quickly mark delimiters straight from normal mode, e.g.

![](http://v0.io/dl/multiedit.gif)

But you can do this from visual mode, so you're right, it's disruptive (and shouldn't override user customization!). I will push a fix in a couple minutes.

**Comment by justbur** [comment]
Maybe in the future you could use the syntax table of the major-mode so that you don't accidentally grab parts of symbols?

**Comment by hlissner** [comment]
Great idea. Problem is I'm not familiar with how to use the syntax table. I'll look into it.

**Comment by justbur** [comment]
Here are some references:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html#Regexp-Backslash

https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Class-Table.html#Syntax-Class-Table
